# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy Vue.js frontend

on:
  push:
    branches: [ deploy ]

jobs:
  build-and-deploy:
    name: Build an Deploy Vue.js App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version:  '12.x'
      - name: Install Dependencies ans build
        run: |
          npm install
          npm run build
      - name: Deploy VueJS app
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          password: ${{secrets.SSH_PASSWORD}} 
          source: ./dist/*
          target: /var/www/kabelsalat
